<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <JellyfinAbi Condition="'$(JellyfinAbi)' == ''">10.10</JellyfinAbi>
    <TargetFramework Condition="'$(JellyfinAbi)' == '10.10'">net8.0</TargetFramework>
    <TargetFramework Condition="'$(JellyfinAbi)' == '10.11'">net9.0</TargetFramework>
    <TargetFramework Condition="'$(JellyfinAbi)' == '12'">net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Jellyfin.Plugin.BiliArchive\Jellyfin.Plugin.BiliArchive.csproj" />
  </ItemGroup>
</Project>
